branch-defaults:
  master:
    environment: blocmaps-env
global:
  application_name: research-development
  default_ec2_keyname: RnD
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
